# Generated by Django 5.0.3 on 2024-03-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='date',
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateField(default='2004-02-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2004-02-11'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='AdminProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.setting')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
            ],
            options={
                'unique_together': {('admin', 'project')},
            },
        ),
    ]
